{
 "title": "T-RMM Agent",
 "tags": [ "TRMMAgentDashboard" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Client",
    "label": "Client",
    "query": "SELECT name FROM clients_client"
   },
   {
    "name": "Sites",
    "label": "Site",
    "query": "SELECT\n    clients_site.name\nFROM\n    clients_site\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\nWHERE\n    clients_client.name IN ($Client)"
   },
   {
    "name": "Agent",
    "label": "Agent",
    "query": "SELECT\n    agents_agent.hostname\nFROM\n    agents_agent\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\nWHERE\n    clients_client.name IN ($Client)\n    AND clients_site.name IN ($Sites)"
   },
   { "name": "Tactical", "query": "postgres" },
   { "name": "TacticalURL", "query": "rmm.genevois-informatique.com" },
   {
    "name": "GrafanaURL",
    "query": "rmm.genevois-informatique.com:3000"
   }
  ]
 },
 "panels": [
  { "title": "Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  COUNT(DISTINCT clients_client.id) AS \"Number of Clients\"\nFROM clients_client\nINNER JOIN clients_site ON clients_site.client_id = clients_client.id\nWHERE \n  clients_site.name IN ($Sites)\n  AND clients_client.name IN ($Client);\n"
    }
   ]
  },
  {
   "title": "Agents",
   "type": "stat",
   "description": "Agents at selected clients/sites",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM agents_agent\nwhere \n  site_id IN (SELECT id FROM clients_site WHERE site_id IN (SELECT id FROM clients_site WHERE name IN ($Sites))) and\n  site_id IN (SELECT id FROM clients_site WHERE client_id IN (SELECT id FROM clients_client WHERE name IN ($Client)))\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Information Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(\n  (SELECT\n    count(*)\n  FROM\n    alerts_alert\n    LEFT JOIN checks_check on alerts_alert.assigned_check_id = checks_check.id\n    LEFT JOIN autotasks_automatedtask on alerts_alert.assigned_task_id = autotasks_automatedtask.id\n    INNER JOIN agents_agent ON autotasks_automatedtask.agent_id = agents_agent.id\n    OR checks_check.agent_id = agents_agent.id\n    OR alerts_alert.agent_id = agents_agent.id\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\n  WHERE\n    clients_client.name IN ($Client)\n    AND clients_site.name IN ($Sites)\n    AND alerts_alert.severity = 'info'\n    AND alerts_alert.resolved = false\n  ),\n  ' / ',\n  (SELECT\n    count(*)\n  FROM\n    alerts_alert\n  WHERE\n    alerts_alert.severity = 'info'\n    AND alerts_alert.resolved = false\n  )\n)"
    }
   ]
  },
  {
   "title": "Warning Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(\n  (SELECT\n    count(*)\n  FROM\n    alerts_alert\n    LEFT JOIN checks_check on alerts_alert.assigned_check_id = checks_check.id\n    LEFT JOIN autotasks_automatedtask on alerts_alert.assigned_task_id = autotasks_automatedtask.id\n    INNER JOIN agents_agent ON autotasks_automatedtask.agent_id = agents_agent.id\n    OR checks_check.agent_id = agents_agent.id\n    OR alerts_alert.agent_id = agents_agent.id\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\n  WHERE\n    clients_client.name IN ($Client)\n    AND clients_site.name IN ($Sites)\n    AND alerts_alert.severity = 'warning'\n    AND alerts_alert.resolved = false\n  ),\n  ' / ',\n  (SELECT\n    count(*)\n  FROM\n    alerts_alert\n  WHERE\n    alerts_alert.severity = 'warning'\n    AND alerts_alert.resolved = false\n  )\n)"
    }
   ]
  },
  {
   "title": "Error Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(\n  (SELECT\n    count(*)\n  FROM\n    alerts_alert\n    LEFT JOIN checks_check on alerts_alert.assigned_check_id = checks_check.id\n    LEFT JOIN autotasks_automatedtask on alerts_alert.assigned_task_id = autotasks_automatedtask.id\n    INNER JOIN agents_agent ON autotasks_automatedtask.agent_id = agents_agent.id\n    OR checks_check.agent_id = agents_agent.id\n    OR alerts_alert.agent_id = agents_agent.id\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\n  WHERE\n    clients_client.name IN ($Client)\n    AND clients_site.name IN ($Sites)\n    AND alerts_alert.severity = 'error'\n    AND alerts_alert.resolved = false\n  ),\n  ' / ',\n  (SELECT\n    count(*)\n  FROM\n    alerts_alert\n  WHERE\n    alerts_alert.severity = 'error'\n    AND alerts_alert.resolved = false\n  )\n)"
    }
   ]
  },
  {
   "title": "WP Updates",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Plugin",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mainwp_updates",
     "query": "SELECT last(\"plugin_updates\") FROM \"mainwp_updates\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "plugin_updates" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Theme",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mainwp_updates",
     "query": "SELECT mean(\"plugin_updates\") FROM \"mainwp_updates\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "theme_updates" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Traduction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mainwp_updates",
     "query": "SELECT last(\"translation_updates\") FROM \"mainwp_updates\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "translation_updates" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Cores",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mainwp_updates",
     "query": "SELECT mean(\"plugin_updates\") FROM \"mainwp_updates\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "wordpress_updates" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Agent Status",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \n  clients_client.name AS \"Client\",  -- Nom du client ajouté en première colonne\n  clients_site.name AS \"Site\",\n  \n  -- Logo en fonction de l'Operating System et des versions spécifiques de Windows\n  CASE\n      WHEN agents_agent.operating_system ILIKE '%Windows 11%' THEN 'https://img.icons8.com/color/512/windows-11.png'\n      WHEN agents_agent.operating_system ILIKE '%Windows 10%' THEN 'https://img.icons8.com/color/512/windows-10.png'\n      WHEN agents_agent.operating_system ILIKE '%Windows 7%' THEN 'https://img.icons8.com/color/512/windows-7.png'\n      WHEN agents_agent.operating_system ILIKE '%Windows Server%' THEN 'https://img.icons8.com/?size=100&id=cqhNzxHz0MMy&format=png&color=000000'\n      WHEN agents_agent.operating_system ILIKE '%macOS%' THEN 'https://img.icons8.com/color/512/mac-os.png'\n      WHEN agents_agent.operating_system ILIKE '%Debian%' THEN 'https://img.icons8.com/color/512/debian.png'\n      WHEN agents_agent.operating_system ILIKE '%Ubuntu%' THEN 'https://img.icons8.com/color/512/ubuntu.png'\n      ELSE 'https://example.com/unknown-os-logo.png'\n  END AS \"OS\",  -- Logo basé sur l'OS\n\n  -- Logo pour Server / Workstation\n  CASE\n      WHEN agents_agent.monitoring_type ILIKE '%server%' THEN 'https://img.papamica.com/icon/server.png'\n      ELSE 'https://cdn-icons-png.flaticon.com/512/4703/4703644.png'\n  END AS \"Type\",  -- Logo basé sur le type (Server ou Workstation)\n\n  agents_agent.hostname AS \"Hostname\",\n  agents_agent.id AS \"AgentID\",\n\n  -- Lien de connexion (string_value du field_id = 4)\n  COALESCE((\n      SELECT \n          string_value \n      FROM agents_agentcustomfield \n      WHERE agent_id = agents_agent.id \n      AND field_id = 4\n  ), 'No Link') AS \"connect_url\",  -- Récupère le lien de connexion du champ personnalisé\n  'https://cdn-icons-png.flaticon.com/128/10337/10337331.png' as \"🔗\",\n  'https://genevois-informatique.com/wp-content/uploads/2024/05/cropped-logo-01-cb-1.png' as \"RMM\",\n  'https://grafana.com/static/assets/img/fav32.png' as \"Stats\",\n  \n  -- Status: Online/Offline basé sur la dernière vue\n  (\n        CASE\n            WHEN last_seen > NOW() - interval '1 minute' THEN 'Online'\n            ELSE 'Offline'\n        END\n    ) AS \"Status\",\n  \n  -- Statut combiné Bitdefender et antivirus Windows : OK si l'un des deux est OK, sinon ERROR, OK par défaut si OS n'est pas Windows\n  CASE\n      WHEN agents_agent.operating_system NOT ILIKE '%Windows%' THEN 'OK'\n      WHEN EXISTS (\n          SELECT 1 \n          FROM checks_checkresult \n          WHERE agent_id = agents_agent.id \n          AND assigned_check_id IN (21, 33) \n          AND retcode = 0\n      ) THEN 'OK'\n      ELSE 'ERROR'\n  END AS \"Antivirus\",\n\n  -- Statut combiné pour Acronis et backup test (Check ID 22 et 35)\n  CASE\n      WHEN EXISTS (\n          SELECT 1\n          FROM checks_checkresult\n          WHERE agent_id = agents_agent.id\n          AND assigned_check_id IN (22, 35)\n          AND retcode = 3\n      ) THEN 'NO'\n      WHEN EXISTS (\n          SELECT 1\n          FROM checks_checkresult\n          WHERE agent_id = agents_agent.id\n          AND assigned_check_id IN (22, 35)\n          AND retcode = 0\n      ) THEN 'OK'\n      ELSE 'ERROR'\n  END AS \"Backup\",\n\n  -- Colonne Update (mises à jour en attente)\n  COALESCE((\n      SELECT\n          CASE \n              WHEN EXISTS \n              (\n                  SELECT * \n                  FROM public.winupdate_winupdate \n                  WHERE action = 'approve' \n                  AND installed = 'False' \n                  AND agent_id = agents_agent.id\n              )\n              THEN 'WARNING'\n              ELSE ''\n          END\n  ), '') AS \"Update\",\n\n  -- Reboot en attente (basé sur le champ `needs_reboot`)\n  CASE\n    WHEN agents_agent.needs_reboot = true THEN 'WARNING'\n  END AS \"Reboot\",\n\n  -- Last Response en format relatif déplacé à la fin\n  CASE\n      WHEN age(NOW(), last_seen) < interval '1 minute' THEN 'Just now'\n      WHEN age(NOW(), last_seen) < interval '1 hour' THEN concat(extract(minute from age(NOW(), last_seen)), ' minutes ago')\n      WHEN age(NOW(), last_seen) < interval '1 day' THEN concat(extract(hour from age(NOW(), last_seen)), ' hours ago')\n      ELSE concat(extract(day from age(NOW(), last_seen)), ' days ago')\n  END AS \"Last Response\",\n  \n  -- Last Reboot en format relatif déplacé à la fin\n  CASE\n      WHEN age(NOW(), to_timestamp(boot_time)) < interval '1 minute' THEN 'Just now'\n      WHEN age(NOW(), to_timestamp(boot_time)) < interval '1 hour' THEN concat(extract(minute from age(NOW(), to_timestamp(boot_time))), ' minutes ago')\n      WHEN age(NOW(), to_timestamp(boot_time)) < interval '1 day' THEN concat(extract(hour from age(NOW(), to_timestamp(boot_time))), ' hours ago')\n      ELSE concat(extract(day from age(NOW(), to_timestamp(boot_time))), ' days ago')\n  END AS \"Last Reboot\"\n\nFROM agents_agent\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\nWHERE\n    clients_client.name IN ($Client)\n    AND clients_site.name IN ($Sites);\n"
    }
   ]
  },
  {
   "title": "Error Messages",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT \n    -- Date en format relatif\n    CASE\n        WHEN age(NOW(), alerts_alert.alert_time) < interval '1 minute' THEN 'Just now'\n        WHEN age(NOW(), alerts_alert.alert_time) < interval '1 hour' THEN concat(extract(minute from age(NOW(), alerts_alert.alert_time)), ' minutes ago')\n        WHEN age(NOW(), alerts_alert.alert_time) < interval '1 day' THEN concat(extract(hour from age(NOW(), alerts_alert.alert_time)), ' hours ago')\n        ELSE concat(extract(day from age(NOW(), alerts_alert.alert_time)), ' days ago')\n    END AS \"Date\",\n\n    alerts_alert.message AS \"Message\",\n    agents_agent.agent_id,\n    'https://genevois-informatique.com/wp-content/uploads/2024/05/cropped-logo-01-cb-1.png' AS \"RMM\"\nFROM alerts_alert\n    LEFT JOIN checks_check ON alerts_alert.assigned_check_id = checks_check.id\n    LEFT JOIN autotasks_automatedtask ON alerts_alert.assigned_task_id = autotasks_automatedtask.id\n    INNER JOIN agents_agent ON autotasks_automatedtask.agent_id = agents_agent.id\n                            OR checks_check.agent_id = agents_agent.id\n                            OR alerts_alert.agent_id = agents_agent.id\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\nWHERE\n  clients_client.name IN ($Client)\n  AND clients_site.name IN ($Sites)\n  AND alerts_alert.severity = 'error' \n  AND alerts_alert.resolved = false;\n"
    }
   ]
  },
  {
   "title": "OS Type",
   "type": "piechart",
   "description": "List all OS installed",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  count(*) as \"count\",\r\n  SUBSTRING(agents_agent.operating_system,'(.*)(?:,|x86_64)') AS \"Operating System\"\r\nFROM agents_agent\r\n  INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\r\n  INNER JOIN clients_client ON clients_site.client_id = clients_client.id\r\nWHERE\r\n  clients_client.name IN ($Client)\r\n  AND clients_site.name IN ($Sites)\r\nGroup by \"Operating System\"\r\nOrder by \"count\" desc\r\n  "
    }
   ]
  },
  {
   "title": "OS Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  select (\r\nSELECT\r\n  count(*)\r\n  FROM agents_agent\r\nWhere\r\n  SUBSTRING(agents_agent.operating_system,POSITION(',' in agents_agent.operating_system)+2,2) = '64' and\r\n  site_id IN (SELECT id FROM clients_site WHERE site_id IN (SELECT id FROM clients_site WHERE name IN ($Sites))) and\r\n  site_id IN (SELECT id FROM clients_site WHERE client_id IN (SELECT id FROM clients_client WHERE name IN ($Client)))) as \"64 Bit\",\r\n\r\n  (SELECT\r\n  count(*)\r\n  FROM agents_agent\r\nWhere\r\n  SUBSTRING(agents_agent.operating_system,POSITION(',' in agents_agent.operating_system)+2,2) = '32' and\r\n   site_id IN (SELECT id FROM clients_site WHERE site_id IN (SELECT id FROM clients_site WHERE name IN ($Sites))) and\r\n  site_id IN (SELECT id FROM clients_site WHERE client_id IN (SELECT id FROM clients_client WHERE name IN ($Client)))) as \"32 Bit\" "
    }
   ]
  },
  {
   "title": "Type of CPUs",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    count(*) as \"count\",\n    (CASE \n      WHEN wmi_detail->'cpu' IS NOT NULL\n      THEN SUBSTRING(agents_agent.wmi_detail->'cpu'->0->0->>'Name','(?:AMD|Intel\\(R\\)|Intel)(.*)(?:@|Processor|with)')\n      ELSE SUBSTRING(agents_agent.wmi_detail->'cpus'->>0,'(?:AMD|Intel\\(R\\)|Intel)(.*)(?:@|Processor|with)')\n    END) as \"CPU Name\"\nFROM agents_agent\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\nWHERE\n  clients_client.name IN ($Client)\n  AND clients_site.name IN ($Sites)\nGroup by \"CPU Name\"\nOrder by \"count\" desc"
    }
   ]
  },
  {
   "title": "Installed System RAM",
   "type": "piechart",
   "description": "List all installed memory",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT \r\n  count(*) as \"count\",\r\n  concat((total_ram),' GB') as \"Size Memory\"\r\n  FROM agents_agent\r\nINNER JOIN clients_site on site_id = clients_site.id\r\nWHERE site_id IN (SELECT id FROM clients_site WHERE client_id IN (SELECT id FROM clients_client WHERE name IN ($Client)))\r\nAND site_id IN (SELECT id FROM clients_site WHERE site_id IN (SELECT id FROM clients_site WHERE name IN ($Sites)))\r\nGroup by \"Size Memory\"\r\nOrder by \"count\" desc\r\n  "
    }
   ]
  },
  { "title": "[$Client] - $Sites - $Agent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }, "repeat": "Agent" },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  CONCAT('[', clients_client.name, '] - ', clients_site.name, ' - ', agents_agent.hostname, '  (', agents_agent.description,')')\nFROM \n  agents_agent\nLEFT OUTER JOIN clients_site ON agents_agent.site_id = clients_site.id\nLEFT OUTER JOIN clients_client ON clients_site.client_id = clients_client.id\nWHERE \n  agents_agent.hostname = '${Agent:raw}';\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  concat(\r\n          to_char(now() - to_timestamp(boot_time) ,'DD' ),' Days ', \r\n          to_char(now() - to_timestamp(boot_time),'HH24' ), ' Hours ',\r\n          to_char(now() - to_timestamp(boot_time),'MI' ), ' Minutes '\r\n        )\r\nFrom \r\n  agents_agent\r\nWhere\r\n  agents_agent.hostname = '${Agent:raw}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 41 },
   "targets": [
    {
     "rawSql": "select   \r\nCASE\r\n  WHEN (count(*) = 1) THEN 'Connected'\r\n  WHEN (count(*) = 0) THEN 'Not Connected'\r\n  ELSE ''\r\n END AS modifiedpvc\r\n  \r\n from \r\n  agents_agent\r\n where \r\n   agents_agent.hostname = '${Agent:raw}'  and\r\n   last_seen > NOW()- interval '1 hours'\r\n "
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Track memory consumption for the selected agent.",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  x AS \"time\",\r\n  y as \"Memory Usage\"\r\nFROM \r\n  checks_checkhistory\r\nWHERE \r\n  x BETWEEN $__timeFrom() AND $__timeTo() AND \r\n  check_id IN (SELECT id FROM checks_check WHERE check_type='memory') AND agent_id=(SELECT agent_id FROM agents_agent where agents_agent.hostname = '${Agent:raw}')\r\n  ORDER BY x"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "table",
   "description": "Total free disk space",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 41 },
   "targets": [
    {
     "rawSql": "select \r\n  concat(items.device,'\\ ', items.free,' free on ',items.total)\r\nfrom \r\n  agents_agent,\r\n  jsonb_to_recordset(disks) as items(device text, free text, total text)\r\nWhere\r\n  agents_agent.hostname = '${Agent:raw}'"
    }
   ]
  },
  {
   "title": "Operating System",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select   \r\nSUBSTRING(agents_agent.operating_system,'(.*)(?:,|x86_64)')\r\n  \r\nfrom \r\n  agents_agent\r\nwhere \r\n     agents_agent.hostname = '${Agent:raw}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE WHEN EXISTS \n    (\n        SELECT * FROM public.winupdate_winupdate WHERE action='approve' AND installed='False' AND agent_id=(SELECT id FROM agents_agent where agents_agent.hostname = '${Agent:raw}')\n    )\n    THEN 'Windows not up to date'\n    ELSE 'Windows up to date'\nEND AS  Status"
    }
   ]
  },
  {
   "title": "CPU Model",
   "type": "stat",
   "description": "Type of CPU installed",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "select  \n  wmi_detail,\n  CASE \n    WHEN wmi_detail->'cpu' IS NOT NULL\n    THEN concat(wmi_detail->'cpu'->0->0->>'Name',' \\ ',wmi_detail->'base_board'->0->0->>'Manufacturer')\n    ELSE concat(wmi_detail->'cpus'->>0)\n  END\nfrom \n  agents_agent\nwhere \n   agents_agent.hostname = '${Agent:raw}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 45 },
   "targets": [
    {
     "rawSql": "select\n  CASE\n   WHEN (agents_agent.needs_reboot = true) THEN 'Reboot required'\n    WHEN (agents_agent.needs_reboot = false) THEN 'No reboot required'\n  ELSE 'nothing'\n END AS  Status\nFrom \n  agents_agent\nWhere\n  agents_agent.hostname = '${Agent:raw}'\n"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "description": "Track CPU consumption for the selected agent.",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  x AS \"time\",\r\n  y as \"CPU Load\"\r\n  FROM checks_checkhistory\r\n  \r\n  WHERE x BETWEEN $__timeFrom() and $__timeTo() --'2021-07-01T13:54:25.526Z' AND '2100-07-02T19:54:25.526Z'\r\n  AND check_id IN (SELECT id FROM checks_check WHERE check_type='cpuload') AND agent_id=(SELECT agent_id FROM agents_agent where agents_agent.hostname = '${Agent:raw}')\r\n  ORDER BY x"
    }
   ]
  },
  {
   "title": "Drive Usage",
   "type": "timeseries",
   "description": "Track disk consumption for the selected agent.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  x AS \"time\",\r\n  y as \"Disk Usage\"\r\nFROM \r\n  checks_checkhistory\r\nWHERE \r\n   x BETWEEN $__timeFrom() AND $__timeTo() \r\n  AND check_id IN (SELECT id FROM checks_check WHERE check_type='diskspace') AND agent_id=(SELECT agent_id FROM agents_agent where agents_agent.hostname = '${Agent:raw}')\r\n  ORDER BY x"
    }
   ]
  },
  {
   "title": "System Ram",
   "type": "stat",
   "description": "Total Agent Memory",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select   \r\n   concat((total_ram),'GB / ',concat(wmi_detail->'mem'->0->0->>'Speed','MHz'))\r\n  \r\nfrom \r\n  agents_agent\r\nwhere \r\n  agents_agent.hostname = '${Agent:raw}'"
    }
   ]
  },
  {
   "title": "BitDefender",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE \n        WHEN retcode = 0 THEN 'OK'\n        WHEN retcode = 1 THEN 'ERROR'\n        WHEN retcode = 2 THEN 'WARNING'\n        ELSE 'Check result not found'\n    END AS Status,\n    substring(stdout, 'Last scan: (\\d{2}\\.\\d{2}\\.\\d{4} \\d{2}:\\d{2}:\\d{2})') AS LastScanDate\nFROM checks_checkresult\nWHERE assigned_check_id = 21\nAND agent_id = (SELECT id FROM agents_agent WHERE agents_agent.hostname = '${Agent:raw}');\n"
    }
   ]
  },
  {
   "title": "Disk Model",
   "type": "stat",
   "description": "Disk model",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT\n  wmi_detail,\n  CASE\n    WHEN wmi_detail->'disk' IS NOT NULL\n    THEN concat(\n      wmi_detail->'disk'->0->0->>'Model', ' / ',  -- Modèle du disque (ex: SSD/HDD)\n      round((wmi_detail->'disk'->0->0->>'Size')::bigint / (1024*1024*1024), 2), ' GB'  -- Taille du disque en GB\n    )\n    ELSE 'Disk information not available'\n  END AS DiskInfo\nFROM\n  agents_agent\nWHERE\n  agents_agent.hostname = '${Agent:raw}';\n"
    }
   ]
  },
  {
   "title": "Acronis",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE \n        WHEN retcode = 0 THEN 'OK'\n        WHEN retcode = 1 THEN 'ERROR'\n        WHEN retcode = 2 THEN 'WARNING'\n        ELSE 'Check result not found'\n    END AS Status,\n    substring(stdout, 'Last backup date: (\\d{2}\\.\\d{2}\\.\\d{4} \\d{2}:\\d{2}:\\d{2})') AS LastBackupDate\nFROM checks_checkresult\nWHERE assigned_check_id = 22\nAND agent_id = (SELECT id FROM agents_agent WHERE agents_agent.hostname = '${Agent:raw}');\n"
    }
   ]
  }
 ]
}